language: objective-c
osx_image: xcode10
podfile: ios/Podfile
before_install:
  - openssl aes-256-cbc -K $encrypted_91d26112053f_key -iv $encrypted_91d26112053f_iv -in development-cert.cer.enc -out development-cert.cer -d
install: true
script: true
