language: node_js
node_js: lts/*
install: true
script:
  - echo $TRAVIS_EVENT_TYPE
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_COMMIT_MESSAGE
branches:
  only:
    - develop
    - develop-native
    - master
