matrix:
  include:
    - # require the branch name to be develop
      if: branch = develop
      language: node_js
      node_js: lts/*
      sudo: true
      before_install:
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list 
        - sudo apt-get update && sudo apt-get install yarn
        - sudo npm install -g expo-cli@2.2.0
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      cache:
        yarn: true
      install:
        - yarn install
      script:
        - expo publish --release-channel $TRAVIS_PULL_REQUEST 
    - # require the branch name to be develop-native
      if: branch = develop-native
      language: android
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-26.0.2
          - build-tools-27.0.3
          - android-26
          - android-27
          - addon-google_apis-google-26
      sudo: true
      env:
        global:
          secure: "AeaYZ4rpZeFrXIjvVMuSdetQopoc3wdQD763szNzrsaNcBmZmNmJNi34hja4h0Plq8OOJDhUyJxYPOQdI1PT4OwjnzWjBPpKjPYDl/eArO2PKUL5BL39/I8WtMNxg+ycR4pKjdqDu+mNci3qKUK9bi+DqdRvQqAasJppiBmbeWSQF95bdSSiqaa8r8OPFOeLHH39HHVkfCJenzeQnllEDE4DVNTlYzKDJg3sv5n0OW/tlUt9lpzqQ/EtdGW3G/pxRRoWHS6AyrRnDt/IszBmYYDgcZ9kWpnXsdAzZ4tCCJ+AlzRtCwGrLws16AQBBfcQqcvgALbcQ2tR7qarmUXXJHv2p0wTK/67xbjARx3dAUJmbMjd7oBhEGsnZDreiWn4hlkH3wyHjKtgRt/80m+sbdR4tJFTRWVIV8jOcA+zwMjMCJ/fE80Obq/z6jH+GpIkuQ1hIC9uvWpxyrn0mIiVmTAlTtYmA2Yj4UBpXfAl08vAdZuwGD8QwfPOt3/BbsV2Krk0fGDBLAS0RMVktwYc9psNY2gJXjgt0dE/PBMIkOkFjxFXzJx/nuv+k7QRJFZL6TWQNtuPNIKdTkopnVvwArlU6HEo8V0bi/bnNMSCerIU8vXG8YbyX7xg861TSPYpHqeDcwq9aA6DelA6mpm40aSbNJkbit+PzSZOtzEsw0U="
      before_install:
        - cd android && echo $gpg_password | gpg --passphrase-fd 0 gradle.properties.gpg && cd .. 
        - cd android/app && echo $gpg_password | gpg --passphrase-fd 0 my-release-key.keystore.gpg && cd ../.. 
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list 
        - sudo apt-get update && sudo apt-get install yarn
        - sudo npm install -g expo-cli@2.2.0
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      install:
        - yarn install
      script:
        - expo publish --release-channel $TRAVIS_PULL_REQUEST 
        - sh release-channel-patch.sh
        - cd android && ./gradlew assembleRelease && cd ..
        - node deploy.js
    - # require the branch name to be master
      if: branch = master
      language: node_js
      node_js: lts/*
      install: true
      script: echo "MASTER BRANCH TEST"
