language: objective-c
osx_image: xcode10
before_install:
  - openssl aes-256-cbc -K $encrypted_91d26112053f_key -iv $encrypted_91d26112053f_iv -in development-cert.cer.enc -out development-cert.cer -d
  - openssl aes-256-cbc -K $encrypted_91d26112053f_key -iv $encrypted_91d26112053f_iv -in development-key.p12.enc -out development-key.p12 -d
  - openssl aes-256-cbc -K $encrypted_91d26112053f_key -iv $encrypted_91d26112053f_iv -in reactnativescaffolddev.mobileprovision.enc -out reactnativescaffolddev.mobileprovision -d
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8.12.0
  - brew install yarn --without-node
  - npm install -g expo-cli@2.2.0
  - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
install:
  - yarn install
script:
  - sh ios.sh
